version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging / auth in to Amazon ECR
       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 766461277699.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - echo Building the docker image
      - docker build -t yt-video-image .
      - docker tag yt-video-image:latest 766461277699.dkr.ecr.us-east-1.amazonaws.com/yt-video-image:latest


  post_build:
    commands:
     - echo build completed
     - echo pushing in to docker ECR...
     - docker push 766461277699.dkr.ecr.us-east-1.amazonaws.com/yt-video-image:latest
     - echo Writing image definition file..
     - printf '[{"name":"%s","imageUri":"%s"}]' "yt-video-service" "766461277699.dkr.ecr.us-east-1.amazonaws.com/yt-video-image" > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
